project:
  type: website
  output-dir: docs

website:
  title: "2025 WFA R Coding Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - StartHere.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

